name: abelhas
description: "A new Flutter project android."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mobile_scanner: ^3.5.7
  qr_flutter: ^4.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  screenshot: ^1.3.0


flutter:
  uses-material-design: true
